[Tests-Only]Add k6 test to restore large number of files from trashbin
owncloud/cdperf pull request #10
Opened 2021-04-13 03:52 UTC by HariBhandari07

2021-04-19 21:10 UTC, fschade commented
@HariBhandari07, thank you for your work. Looks good to me.
Just some minor questions:

The test is running  for 200000 iterations with a max duration of 1000m... should it run as part of the regular performance tests or is meant to be some kind of a red green test?

2021-04-21 08:11 UTC, HariBhandari07 commented
@fschade the test is running for 200k iterations just to demonstrate the issue and the max duration of 1000m // 6000m is just some random duration so that the test won't stop as time runs out. The test is just some kind of red-green test.

2021-04-21 08:22 UTC, fschade commented
ok then we can disable it in the regular 3 weekly performance runs right? Have you plans to backport the api requests to the lib or should they stay in the script?

2021-04-22 12:23 UTC, HariBhandari07 commented
> ok then we can disable it in the regular 3 weekly performance runs right? Have you plans to backport the api requests to the lib or should they stay in the script?

Yup, no need to run this regularly in 3 weekly performance runs.

2021-04-29 12:26 UTC, phil-davis commented
I added this to the QA project so that someone sees it and can look at what @HariBhandari07 was doing here and move it forward.

2021-04-29 12:29 UTC, fschade commented
> was

thanks phil, i already talked to @HariBhandari07 and he hended the current status over to me. I need to refactor the called endboints back to the playbooks so that they can be reused in future tests

2022-02-10 14:30 UTC, dragotin requested changes
Thanks a lot for your contribution.

We added a test description doc in `docs/tests.md`.

Do you mind rebasing and adding some description about these new tests? Thanks a lot.

2022-02-11 08:21 UTC, phil-davis commented
Hari has left us. @fschade are you going to look at this, or will I take it?

2022-02-21 12:49 UTC, fschade commented
@phil-davis If you find time to check it out that would be great

2022-06-21 11:43 UTC, fschade commented
@individual-it you ha a chance to have a look?

2022-06-21 14:17 UTC, butonic commented
https://github.com/owncloud/cdperf/pull/16 has been merged, closing this. Please reopen if necessary.

2022-06-21 14:17 UTC, closed without merging

2022-06-21 14:25 UTC, individual-it commented
sorry this was not picked up for a long time