Refactor propfind tests and add a new one
owncloud/cdperf pull request #18
Opened 2021-11-22 20:50 UTC by fschade

# Description
Today we discussed that we need another propfind test with a deeper nested folder structure, in this breath i refactored those to use a shared lib which makes developing propfind tests more easy. Cc.: @dragotin & @ScharfViktor 

To keep the old results meaningful the test with a nesting count of 5 is still there.

# Changes
* linted project files
* refactor to shared propfind lib
* add new propfind test with a depth of 45

# ToDos
* find a better test naming to keep the files meaningful

2021-11-24 12:59 UTC, ScharfViktor commented
run k6 test with docker ocis and local k6: `./scripts/cdperf --cloud-vendor=ocis --k6-test-host=https://localhost:9200 --k6-docker=false`
branch: `propfind-tests`
env: macOc Big Sur v.11.4 M1

tests was succeful: 

- [ ] deep_1000_files_5_nested_folders.ts
- [ ] deep_1000_files_45_nested_folders.ts
- [ ] deep_1000_files.ts

small finding, here it try to run file `lib.ts`:
 
![Screenshot 2021-11-24 at 13 55 58](https://user-images.githubusercontent.com/84779829/143242973-5ab6d57e-9129-41c5-a502-835ba4f8a346.png)

2021-11-24 13:12 UTC, fschade commented
> run k6 test with docker ocis and local k6: `./scripts/cdperf --cloud-vendor=ocis --k6-test-host=https://localhost:9200 --k6-docker=false` branch: `propfind-tests` env: `macOc Big Sur v.11.4 M1`
> 
> ### tests were successful:
> * [x]  deep_1000_files_5_nested_folders.ts
> * [x]  deep_1000_files_45_nested_folders.ts
> * [x]  deep_1000_files.ts
> 
> small finding, here it try to run file `lib.ts`:
> 
> ![Screenshot 2021-11-24 at 13 55 58](https://user-images.githubusercontent.com/84779829/143242973-5ab6d57e-9129-41c5-a502-835ba4f8a346.png)

good catch, thanks :) Fixed

2021-11-24 13:17 UTC, ScharfViktor commented
test `deep_1000_files_45_nested_folders.ts` was very long, maybe the depth is too deep: 
![Screenshot 2021-11-24 at 14 07 31](https://user-images.githubusercontent.com/84779829/143244789-d0c3e12a-461b-4432-816c-a0e5b5386fd7.png)

`deep-1000-files-5-nested-folders.js` was `running (0h02m14.1s)`
`propfind-flat-1000-files.js` was `running (0h00m36.0s)`

the result of a remote Intel machine will be faster

2021-11-24 14:16 UTC, ScharfViktor commented
One more thing, the upload test partially failed. This does not seem to be related to your commit, but for your information. Running it again gave the same results

![Screenshot 2021-11-24 at 15 10 55](https://user-images.githubusercontent.com/84779829/143254746-f26cce07-897b-41fd-90db-871b8f9ceb04.png)

2021-11-25 11:58 UTC, fschade commented
> test `deep_1000_files_45_nested_folders.ts` was very long, maybe the depth is too deep: ![Screenshot 2021-11-24 at 14 07 31](https://user-images.githubusercontent.com/84779829/143244789-d0c3e12a-461b-4432-816c-a0e5b5386fd7.png)
> 
> `deep-1000-files-5-nested-folders.js` was `running (0h02m14.1s)` `propfind-flat-1000-files.js` was `running (0h00m36.0s)`
> 
> the result of a remote Intel machine will be faster

cc: @dragotin we need to come up with an concept hof those tests, maybe we can test with a smaller amount of files and still can get a meaningful result... ideas? I say we need to go to the lab and brainstorm

2021-11-25 12:00 UTC, fschade commented
> One more thing, the upload test partially failed. This does not seem to be related to your commit, but for your information. Running it again gave the same results

we need to check and investigate, if the flakyness is in the tests.... this is not good. I bet it's the backend because we hammer it too much, then its a good thing and cdpers presents us the weak spots

2021-11-25 12:29 UTC, dragotin commented
Agreed. If there are failing requests in the the tests, we need to recognize that immediately and fix the backend. The full success of the test should be an acceptance criteria for releases etc.

I think the amount of files should not be the problem. It should be a for the test reasonable, and kind of "serious" amount of files...

2021-11-25 12:48 UTC, fschade commented
> Agreed. If there are failing requests in the the tests, we need to recognize that immediately and fix the backend. The full success of the test should be an acceptance criteria for releases etc.
> 
> I think the amount of files should not be the problem. It should be a for the test reasonable, and kind of "serious" amount of files...

i mentioned the amount because it takes 30 minutes now to get an answer, maybe we can also reduce the amount of files inside a nested folder, be faster and be able to answer the same questions.... just thinking loudly ;)

2021-12-08 11:19 UTC, fschade commented
@dragotin can we discuss the new tests this week, dont wanna have this opened for too long

2021-12-08 22:21 UTC, ScharfViktor approved these changes

2021-12-10 06:19 UTC, individual-it requested changes
I've ran those tests from ` 49.12.163.166` on `49.12.163.186` and they take too long
![image](https://user-images.githubusercontent.com/2425577/145526764-5b8c641a-0d63-4eb8-87fa-e15c837051f9.png)

also some fail
![image](https://user-images.githubusercontent.com/2425577/145526826-e68ed3f3-4210-4013-bc2e-74bf932a69c7.png)

2021-12-10 08:23 UTC, dragotin commented
@individual-it @fschade and me had a brief discussion yesterday and he proposed to run this test with less files to make it run faster. WIP I guess ;-)

2022-02-10 13:52 UTC, dragotin commented
@fschade @ScharfViktor it would be cool to get this in :-)

2022-02-10 13:53 UTC, dragotin approved these changes
My approval, but keep in mind: I am a javascript noob.

2022-02-10 14:30 UTC, dragotin commented
We added a test description doc in `docs/tests.md`.

Do you mind rebasing and adding some description about these new tests? Thanks a lot.

2022-02-11 06:59 UTC, individual-it commented
@fschade what response would you expect if the server is under load? can we code that into the test?
And then the question is if we want to run it also nightly, if yes it would be confusing if there are some failures that we tolerate, because s.o. needs to remember what is tolarable

2022-02-11 08:47 UTC, fschade commented
@individual-it in my opinion its ok if the test fails because of high load. We should not reduce the load to make the result green, instead we should finetune the server to be able to handle it.

2022-02-11 09:46 UTC, individual-it commented
@fschade yes I totally agree, I didn't meant to reduce the load, but wanted to ask  what should happen under high load and if the server reacts correctly now.
E.g. if under high load the server replies with `500 Internal Server Error` I would consider that a bug, if it returns `429 Too Many Requests` it should be OK similar if its a slow 20x

I assumed the server reacts under high load already as it should, if that is the case then I would love to get the tests green.
If the server currently does not what it should do under load, then its a bug and the tests should be red (and hopefully the bug fixed at some point). Still then we need some automated system to tell us what are acceptable failures and what not. Not to cover up any problems but not to get into the habit of: "oh we know some tests fail, we can ignore those". Because potentially those failures will grow over time and not followed up.
E.g. we could setup the graphana notifications to shout only starting above a certain (problematic, but acceptable) threshold.

2022-02-11 10:49 UTC, dragotin commented
Let me try to summarize: 
- It is not ok if the system fails with 500 under high load, but it (probably) is if it returns an 492. 
- Currently we can not really detect that in our framework. That would be a todo.
- To keep the tests meaningful, they have to be green

As long as we can not check if 500 = red test or 492 = green I agree, we need to tweak the test that does not run into the overload. OTOH it would make sense to have this test case to provoke the 500 situation and debug it.

Long story short: For now, we absolutely need a non failing version of the test. Either by debugging the server, enhancing the test to distinguish reply codes or lower the load on the server.

I vote for the latter for now.

2022-02-11 11:16 UTC, fschade commented
thanks for all your feedback, i created a less heavy version of the test. Should be good to go

2022-02-11 12:08 UTC, ScharfViktor reviewed
just one small find

2022-02-11 17:05 UTC, fschade commented on src/k6/src/test/issue/github/ocis/1018/propfind/deep_100_files_45_nested_folders.ts
> +// put 1000 files into nested dirs and run a 'PROPFIND' through API
thanks, resolved

2022-02-11 17:07 UTC, merged

2022-02-14 05:47 UTC, individual-it commented
this resulted in a funny graph https://grafana.k6.infra.owncloud.works/d/8IV_hHt7k/test-durations?orgId=1&from=1644487427677&to=1644755529309
![grafik](https://user-images.githubusercontent.com/2425577/153807042-3dd7b30c-72ad-461f-ae2a-06f3dd30722d.png)

seems like multiple results of the test run are reported. Any idea what happened there?